version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: learn-python-app:0.0.7
    container_name: learn-python-app-container
    volumes:
      - ..:/mnt
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    container_name: learn-python-redis-container
    ports:
      - "6379:6379"