version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: learn-python-app:0.0.3
    container_name: learn-python-app-container
    volumes:
      - ..:/mnt
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/sh -c "while sleep 1000; do :; done"